### ISSUE TITLE
Erro no código

### ISSUE THREAD

**Issue by LESS14** [zHypezinXzL/include-a_curtain-samp#2]
Este issue é ao mesmo tempo uma sugestão e um relato de um erro no código. Ao analisar o código, observei que você está usando a função CallRemoteFunction para chamar callbacks. No entanto, isso está incorreto neste caso. Para chamar callbacks locais(ou seja, aquelas que estão no escopo do arquivo), você deve utilizar a função CallLocalFunction.

A sugestão é incluir o arquivo do código(Que no momento está apenas disponível nos releases) no repositório. Isso facilitaria para as pessoas analisarem o código, pois não precisariam baixar o arquivo. Além disso, permitiria pull requests e blames de maneira mais conveniente.

**Comment by pnb-pontes** [comment]
ok, obrigado pelo feedback!
